# Generated by Django 3.0.5 on 2020-05-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformationmodel',
            name='nike_name',
            field=models.CharField(default='', max_length=50, verbose_name='昵称'),
        ),
    ]
